# Yupeng ZHAO (MT-BA2)
# Update CFILES & run make depend whenever files are added/removed
# 
# Greatly inspired by Prof Ronan Boulic from CS101@EPFL

# Compiler
CC      = gcc

# Include directory
INCLUDE = include

# Compiler flags (-O3 to optimize, -g to debug, -pg or -ftest-coverage -fprofile-arcs to profile)
CFLAGS  = -Wall -Wextra -I${INCLUDE} -pg -g -O2

# Libraries
LIBS    = -lm -L/usr/lib

# Source code to compile
CFILES  = main.c go.c players.c utils.c
CPPFILES = 

# Object files (generated using CFILES)
OFILES  = $(CFILES:.c=.o)

# Target file name
TARGET  = go.x

# Link objects into executable file
$(TARGET): $(OFILES)
	$(CC) $(OFILES) $(CFLAGS) ${LIBS} -o $(TARGET)


# Special targets:
# "make depend" : generate list of dependencies
# "make clean"  : delete *.o *.x files

depend:
	@echo "Generating dependencies..."
	@(sed '/^# DO NOT DELETE THIS LINE/q' Makefile && \
	  $(CC) -MM $(CFLAGS) $(CFILES) | \
	  egrep -v "/usr/include" \
	 ) >Makefile.new
	@mv Makefile.new Makefile
	@echo "Done."

clean:
	@echo "Deleting graphs, object files and executables..."
	@rm -f *.o *.x graph*.json
	@echo "Done."

#
# -- Dependencies generated by "make depend"
#####################################################
# DO NOT DELETE THIS LINE
main.o: main.c go.h players.h utils.h
go.o: go.c go.h utils.h
players.o: players.c players.h go.h utils.h
utils.o: utils.c utils.h
