# Update CFILES & run make depend whenever files are added/removed
# 
# Greatly inspired by Prof Ronan Boulic from CS101@EPFL

# Compiler
CC      = gcc

# Include directory
INCLUDE = .

# Compiler flags (-O3 to optimize, -g to debug, -pg or -ftest-coverage -fprofile-arcs to profile)
CFLAGS  = -Wall -Wextra -I${INCLUDE} -g

# Libraries
LIBS    = -lm -L/usr/lib

# Source code to compile
CFILES  = main.c chess.c utils.c players/human.c players/randy.c players/karl.c players/teresa.c
CPPFILES = 

# Object files (generated using CFILES)
OFILES  = $(CFILES:.c=.o)

# Target file name
TARGET  = chess.x

# Link objects into executable file
$(TARGET): $(OFILES)
	$(CC) $(OFILES) $(CFLAGS) ${LIBS} -o $(TARGET)


# Special targets:
# "make depend" : generate list of dependencies
# "make clean"  : delete *.o *.x files

depend:
	@echo "Generating dependencies..."
	@(sed '/^# DO NOT DELETE THIS LINE/q' Makefile && \
	  $(CC) -MM $(CFLAGS) $(CFILES) | \
	  egrep -v "/usr/include" \
	 ) >Makefile.new
	@mv Makefile.new Makefile
	@echo "Done."

clean:
	@echo "Deleting graphs, object files and executables..."
	@find . -name "*.o" -type f -delete
	@find . -name "*.x" -type f -delete
	@find . -name "DISABLEgraph*.o" -type f -delete
	@echo "Done."

#
# -- Dependencies generated by "make depend"
#####################################################
# DO NOT DELETE THIS LINE
main.o: main.c chess.h players/human.h players.h players/randy.h \
  players/teresa.h utils.h
chess.o: chess.c chess.h rand.h utils.h
utils.o: utils.c utils.h
human.o: players/human.c players/human.h players.h chess.h
randy.o: players/randy.c players/randy.h players.h chess.h
karl.o: players/karl.c players/karl.h players.h chess.h utils.h
teresa.o: players/teresa.c players.h chess.h players/teresa.h utils.h
