# Yupeng ZHAO (MT-BA2)
# Update CFILES & run make depend whenever files are added/removed
# 
# Greatly inspired by Prof Ronan Boulic from CS101@EPFL

# Compiler
CC      = gcc

# Include directory
INCLUDE = include

# Compiler flags (-g to debug, -pg to profile)
CFLAGS  = -Wall -Wextra -I${INCLUDE} -O3

# Libraries
LIBS    = -O3 -lm -L/usr/lib

# Source code to compile
CFILES  = main.c go.c utils.c
CPPFILES = 

# Object files (generated using CFILES)
OFILES  = $(CFILES:.c=.o)

# Target file name
TARGET  = go.x

# Link objects into executable file
$(TARGET): $(OFILES)
	$(CC) $(OFILES) ${LIBS} -o $(TARGET)


# Special targets:
# "make depend" : generate list of dependencies
# "make clean"  : delete *.o *.x files

depend:
	@echo "Generating dependencies..."
	@(sed '/^# DO NOT DELETE THIS LINE/q' Makefile && \
	  $(CC) -MM $(CFLAGS) $(CFILES) | \
	  egrep -v "/usr/include" \
	 ) >Makefile.new
	@mv Makefile.new Makefile
	@echo "Done."

clean:
	@echo "Deleting object files and executables..."
	@rm -f *.o *.x
	@echo "Done."

#
# -- Dependencies generated by "make depend"
#####################################################
# DO NOT DELETE THIS LINE
main.o: main.c go.h
go.o: go.c go.h utils.h
utils.o: utils.c utils.h
